// Mocks generated by Mockito 5.4.6 from annotations
// in class_attendance_frontend/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:class_attendance_frontend/api/attendance_api.dart' as _i7;
import 'package:class_attendance_frontend/models/class_model.dart' as _i8;
import 'package:class_attendance_frontend/models/session_model.dart' as _i3;
import 'package:class_attendance_frontend/models/user.dart' as _i2;
import 'package:class_attendance_frontend/services/auth_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSessionModel_1 extends _i1.SmartFake implements _i3.SessionModel {
  _FakeSessionModel_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<(_i2.User, String)> login(String? userId, String? password) =>
      (super.noSuchMethod(
        Invocation.method(#login, [userId, password]),
        returnValue: _i5.Future<(_i2.User, String)>.value((
        _FakeUser_0(this, Invocation.method(#login, [userId, password])),
        _i6.dummyValue<String>(
          this,
          Invocation.method(#login, [userId, password]),
        ),
        )),
      ) as _i5.Future<(_i2.User, String)>);
}

/// A class which mocks [AttendanceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceApi extends _i1.Mock implements _i7.AttendanceApi {
  MockAttendanceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i8.ClassModel>> getStudentClasses(String? token) =>
      (super.noSuchMethod(
        Invocation.method(#getStudentClasses, [token]),
        returnValue: _i5.Future<List<_i8.ClassModel>>.value(
          <_i8.ClassModel>[],
        ),
      ) as _i5.Future<List<_i8.ClassModel>>);

  @override
  _i5.Future<_i8.ClassModel> getStudentClassDetail(
      String? token,
      String? classId,
      ) =>
      (super.noSuchMethod(
        Invocation.method(#getStudentClassDetail, [token, classId]),
        returnValue: _i5.Future<_i8.ClassModel>.value(
          _i8.ClassModel(
            classId: 'mock',
            className: 'mock',
            credits: 0,
            group: '0',
          ),
        ),
      ) as _i5.Future<_i8.ClassModel>);

  @override
  _i5.Future<List<_i8.ClassModel>> getTeacherClasses(String? token) =>
      (super.noSuchMethod(
        Invocation.method(#getTeacherClasses, [token]),
        returnValue: _i5.Future<List<_i8.ClassModel>>.value(
          <_i8.ClassModel>[],
        ),
      ) as _i5.Future<List<_i8.ClassModel>>);

  @override
  _i5.Future<_i3.SessionModel> createSession(
      String? token,
      String? classId,
      String? lessonId,
      int? level,
      ) =>
      (super.noSuchMethod(
        Invocation.method(#createSession, [token, classId, lessonId, level]),
        returnValue: _i5.Future<_i3.SessionModel>.value(
          _FakeSessionModel_1(
            this,
            Invocation.method(#createSession, [
              token,
              classId,
              lessonId,
              level,
            ]),
          ),
        ),
      ) as _i5.Future<_i3.SessionModel>);

  @override
  _i5.Future<Map<String, dynamic>> getSessionStats(
      String? token,
      String? sessionId,
      ) =>
      (super.noSuchMethod(
        Invocation.method(#getSessionStats, [token, sessionId]),
        returnValue: _i5.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String> checkIn(
      String? token,
      String? sessionId,
      String? nfcCardId, {
        List<double>? faceEmbedding,
      }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIn,
          [token, sessionId, nfcCardId],
          {#faceEmbedding: faceEmbedding},
        ),
        returnValue: _i5.Future<String>.value('mock_class_id'),
        returnValueForMissingStub: _i5.Future<String>.value('mock_class_id'),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> registerFace(
      String? token,
      List<double>? faceEmbedding,
      ) =>
      (super.noSuchMethod(
        Invocation.method(#registerFace, [token, faceEmbedding]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}